import { BodyPart, Equipment, Target } from '../../../../interfaces/exercise';

export const equipment: Equipment[] = [
	'assisted',
	'band',
	'barbell',
	'body weight',
	'bosu ball',
	'cable',
	'dumbbell',
	'elliptical machine',
	'ez barbell',
	'hammer',
	'kettlebell',
	'leverage machine',
	'medicine ball',
	'olympic barbell',
	'resistance band',
	'roller',
	'rope',
	'skierg machine',
	'sled machine',
	'smith machine',
	'stability ball',
	'stationary bike',
	'stepmill machine',
	'tire',
	'trap bar',
	'upper body ergometer',
	'weighted',
	'wheel roller',
];

export const bodyPart: BodyPart[] = ['back', 'cardio', 'chest', 'lower arms', 'lower legs', 'neck', 'shoulders', 'upper arms', 'upper legs', 'waist'];

export const targetFilters: Target[] = [
	'abductors',
	'abs',
	'adductors',
	'biceps',
	'calves',
	'cardiovascular system',
	'delts',
	'forearms',
	'glutes',
	'hamstrings',
	'lats',
	'levator scapulae',
	'pectorals',
	'quads',
	'serratus anterior',
	'spine',
	'traps',
	'triceps',
	'upper back',
];